name: Release

on:
  push:
    branches:
      - DO-1880
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
        with:
          role_name: ${{ secrets.AWS_ROLE_NAME_CONNECTOR_EXTENSION_SECRETS }}
          app_name: 'connector-extension'
          step_name: 'connector-extension-webchrome-store-secrets'
          secret_prefix: 'GH'
          secret_name: ${{ secrets.AWS_CONNECTOR_EXTENSION_WEBCHROME_STORE_SECRET_ARN }}
          parse_json: true

      - name: Echo ExtensionId
        run: echo ${{ secrets.GH_EXTENSION_ID }}
