name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  
jobs:
  test_dev:
    if: ${{ github.base_ref == 'develop' || github.ref_name == 'develop' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: npm ci

      - name: Running lint
        run: npm run lint

      - name: Running unit tests
        run: npm run test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@156db6fef3e168e4972abb76de0b32bbce8ec77a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
